const DIFFICULTY = 3;
const MINE_RATE = 3000;
const MINING_REWARD = 50;

const SENSHAMART_URI_PREFIX = "SSM://";
const SENSHAMART_URI_REPLACE = "SSMS://";

const DEFAULT_UI_HTML = "./ui/wallet-ui.html";
const DEFAULT_UI_JS = "./ui/wallet-logic.js";
const DEFAULT_DEMO_UI_HTML = "./ui/demo-ui.html";
const DEFAULT_DEMO_UI_JS = "./ui/demo-logic.js";

const DEFAULT_PORT_MINER_BASE = 3000;
const DEFAULT_PORT_MINER_API = DEFAULT_PORT_MINER_BASE + 1;
const DEFAULT_PORT_MINER_CHAIN =  DEFAULT_PORT_MINER_BASE + 2;
const DEFAULT_PORT_MINER_TX_SHARE = DEFAULT_PORT_MINER_BASE + 3;
const DEFAULT_PORT_MINER_TX_RECV = DEFAULT_PORT_MINER_BASE + 4;


const DEFAULT_PORT_WALLET_BASE = 4000;
const DEFAULT_PORT_WALLET_API = DEFAULT_PORT_WALLET_BASE + 1;
const DEFAULT_PORT_WALLET_CHAIN = DEFAULT_PORT_WALLET_BASE + 2;

const DEFAULT_PORT_BROKER_BASE = 5000;
const DEFAULT_PORT_BROKER_API = DEFAULT_PORT_BROKER_BASE + 1;
const DEFAULT_PORT_BROKER_CHAIN = DEFAULT_PORT_BROKER_BASE + 2;
const DEFAULT_PORT_BROKER_SENSOR_HANDSHAKE = DEFAULT_PORT_BROKER_BASE + 3;
const DEFAULT_PORT_BROKER_MQTT = DEFAULT_PORT_BROKER_BASE + 4;

const DEFAULT_PORT_SENSOR_BASE = 6000;
const DEFAULT_PORT_SENSOR_API = DEFAULT_PORT_SENSOR_BASE + 1;

module.exports = {
  DIFFICULTY,
  MINE_RATE,
  MINING_REWARD,

  SENSHAMART_URI_PREFIX,
  SENSHAMART_URI_REPLACE,

  DEFAULT_UI_HTML,
  DEFAULT_UI_JS,
  DEFAULT_DEMO_UI_HTML,
  DEFAULT_DEMO_UI_JS,

  DEFAULT_PORT_MINER_API,
  DEFAULT_PORT_MINER_CHAIN,
  DEFAULT_PORT_MINER_TX_SHARE,
  DEFAULT_PORT_MINER_TX_RECV,

  DEFAULT_PORT_WALLET_API,
  DEFAULT_PORT_WALLET_CHAIN,

  DEFAULT_PORT_BROKER_API,
  DEFAULT_PORT_BROKER_CHAIN,
  DEFAULT_PORT_BROKER_SENSOR_HANDSHAKE,
  DEFAULT_PORT_BROKER_MQTT,

  DEFAULT_PORT_SENSOR_API
};